/* ==========================================================================
   YOTSUBA — traducción al inglés
   El español vive en el HTML y se captura solo; aquí solo va el inglés.
   Si añades un texto nuevo en español y olvidas su clave aquí, la web
   muestra el español en vez de romperse.
   ========================================================================== */
window.YOTSUBA_EN = {

  /* ---------------------------------------------------------- comunes --- */
  'a11y.skip': 'Skip to content',
  'plate.index': 'ENUMA ELISH · PAINTED IN KRITA',
  'plate.fw': 'ENUMA ELISH · PAINTED IN KRITA',
  'plate.hy': 'YOTSUBA HYBRID · WATERCOLOUR',
  'plate.en': 'ENUMA ELISH · NEON VARIANT',
  'nav.tag': 'Game Studio',
  'nav.framework': 'Yotsuba Framework', 'nav.hybrid': 'Yotsuba Hybrid', 'nav.engine': 'Yotsuba Engine',
  'nav.precios': 'Pricing', 'nav.comunidad': 'Community',
  'nav.buy': 'Buy', 'nav.label': 'Primary navigation', 'nav.langTo': 'Cambiar idioma a español',
  'foot.docs': 'Documentation',
  'foot.by': 'Developed by',
  'foot.ceo': 'CEO',
  'foot.copy': '© 2026 Yotsuba Studios. All rights reserved.',

  /* ---------------------------------------------------------- portada --- */
  'doc.title': 'Yotsuba — the game development platform with three approaches',
  'doc.desc': 'The only platform that integrates a Game Framework, a Game Engine and a hybrid solution in a single ecosystem. Built on XNA, with DirectX 12, Vulkan, Metal, WebGPU, Compute Shaders and 7 shader languages.',
  'hero.status': 'In development · Coming soon',
  'hero.kick': 'Game Development Platform',
  'hero.h1a': '3 approaches.', 'hero.h1b': '1 ecosystem.',
  'hero.lede': 'The only <b>game development platform</b> that integrates three approaches in a single ecosystem: a <b>Game Framework</b>, a <b>Game Engine</b> and a <b>hybrid</b> solution between the two. Built on XNA and designed for <b>Next-Gen</b> games.',
  'hero.lede2': 'Support for modern graphics technologies — <b>DirectX\u00a012</b>, <b>Vulkan</b>, <b>Metal</b> and <b>WebGPU</b> — plus <b>Compute Shaders</b> and support for <b>7 different shader languages</b>, giving you maximum control, performance and cross-platform flexibility.',
  'hero.demo': 'Try it in your browser',
  'hero.cta2': 'See the three approaches',
  'hero.s1': 'C# / .NET', 'hero.s2': '2D + 3D',
  'hero.s3': 'One payment', 'hero.s4': '0 % royalties',
  'hero.art': 'Yotsuba illustration: a winged figure descends through a stormy sea while two caped travellers and a white tiger watch from the shore',

  'prod.eyebrow': 'One engine underneath, three ways to use it',
  'prod.h': 'Choose where you <em>come in.</em>',

  'pick.folio': 'which one is yours',
  'pick.h': 'How do you like to work?',
  'pick.sub': 'Answer one thing. We will tell you where to start — and no answer locks you in.',
  'pick.aria': 'How do you like to work?',
  'pick.o1': 'I write everything in code', 'pick.o1d': 'Give me a library and my IDE. Nothing else.',
  'pick.o2': 'I want to tweak things while it runs', 'pick.o2d': 'Change values with the game running, without leaving the window.',
  'pick.o3': 'I want to open an editor and press Play', 'pick.o3d': 'Scene, hierarchy, inspector, export. The classic way.',

  'pr.hi': 'Pay once and it is yours.',
  'pr.subi': 'No royalties on what you sell, no per-seat fee and no invoice arriving the day your game does well.',
  'pr.ver': 'See pricing and comparison',

  'co.hi': 'Build it<em>with us.</em>',
  'co.di': 'The project is in development and the road is open. Leave your email and we will tell you when the store opens and when each release lands.',
  'co.cta': 'Tell me when it launches',
  'co.film': 'The Yotsuba Hybrid editor',
  'co.filmA': 'Recording of the Yotsuba editor running',
  'co.filmC': 'Real footage, not a mock-up.',

  /* -------------------------------------------------------- Framework --- */
  'fw.status': 'XNA lineage · a new graphics architecture',
  'fw.h1a': 'Next Gen', 'fw.h1b': 'XNA.',
  'fw.lede': 'The only framework with XNA lineage that modernised its whole graphics architecture: <b>compute shaders</b>, Vulkan, Metal, DirectX&nbsp;12, WebGPU and seven shader languages, with <b>runtime compilation</b>.',
  'fw.demo': 'Run it on your GPU',
  'fw.cta2': 'See the capabilities',
  'fw.s1': 'Compute shaders', 'fw.s2': '7 shader languages', 'fw.s3': 'MonoGame compatible',
  'fw.art': 'Yotsuba Framework illustration',
  'fw.claim': 'An XNA reimplementation built from scratch on today’s graphics architecture. <b>Your MonoGame libraries keep working</b> without a rebuild.',
  'fw.r1': 'Compute shaders', 'fw.r1d': 'Massively parallel GPU work inside an XNA-shaped framework.',
  'fw.r2': 'Seven shader languages', 'fw.r2d': 'MGFX, FNAFX, Slang, HLSL, GLSL, MSL and direct SPIR-V input. Four of them travel to WebGPU.',
  'fw.r3': 'Native graphics paths', 'fw.r3d': 'Vulkan on Android and Linux, Metal on Apple, DirectX 12 on Windows, WebGPU in the browser.',
  'fw.r4': 'The pipeline you know', 'fw.r4d': 'MGCB and MGFX with the DesktopVK profile: no new tooling to learn.',
  'fw.for': 'Nine capabilities, one by one',
  'fw.actB': 'CAPABILITIES',
  'fw.back': '← Back to the three products',
  'fw.cpre': 'Yotsuba Framework',
  'fw.ch': 'Just the library<em>and nothing else.</em>',
  'fw.cd': 'One payment, a perpetual licence and zero royalties on what you sell. If you later want the editor, Hybrid and Engine are one step away.',
  'fw.cbuy': 'Buy Framework', 'fw.ccmp': 'Compare all three',
  'fw.f1': 'API', 'fw.f1d': 'The same surface as MonoGame, FNA and KNI.',
  'fw.f2': 'Graphics', 'fw.f2d': 'Plus WebGPU on the roadmap.',
  'fw.f3': 'Royalties', 'fw.f3d': 'Ship and sell without sharing revenue.',

  /* ----------------------------------------------------------- Hybrid --- */
  'hy.status': 'In development · Coming soon',
  'hy.h1a': 'Framework', 'hy.h1b': 'Engine',
  'hy.lede': 'The visual editor <b>lives inside your game window</b>, not in a separate app. In <code>DEBUG</code> it shows up; when you build in <code>RELEASE</code> it leaves the binary.',
  'hy.cta1': 'See how it works', 'hy.cta2': 'See pricing',
  'hy.s1': 'Editor in the window', 'hy.s2': '4 backends', 'hy.s3': 'Compiles to C#',
  'hy.art': 'Yotsuba Hybrid: a four-leaf clover painted in watercolour',
  'hy.claim': 'Framework and editor in one. You write the game in your IDE, run it, and <b>tune it with the game running</b> without leaving the window.',
  'hy.r1': 'Editor in the window', 'hy.r1d': 'No app switching, no lost context. You edit while the game runs.',
  'hy.r2': 'RELEASE without the editor', 'hy.r2d': 'Compilation directives take the whole editor away. Your binary does not carry it.',
  'hy.r3': 'Four backends', 'hy.r3d': 'MonoGame, KNI, FNA and Yotsuba Framework. Platforms add up, they do not split.',
  'hy.r4': 'It becomes C#', 'hy.r4d': 'What you decide in the editor compiles to code: less JSON at startup, faster loads.',
  'hy.for': 'Yotsuba means “four leaves”',
  'hy.actB': 'THE PILLARS',
  'hy.leavesE': 'Four leaves, four pillars',
  'hy.leavesH': 'Every leaf is <span class="brush">a pillar.</span>',
  'hy.n1': 'The editor inside', 'hy.n2': 'Two layers',
  'hy.n3': 'Platforms add up', 'hy.n4': 'Your code stays yours',
  'hy.p1t': 'The editor lives inside your game, not beside it.',
  'hy.p1d': 'In debug mode, Hybrid opens a visual editor inside the very window your game renders in, not in an external app. You work from your favourite IDE, run it, and edit while it runs in real time.',
  'hy.p1s1': 'Write your game', 'hy.p1s1d': 'Ordinary code, with no ties to a proprietary editor. Your architecture stays yours.',
  'hy.p1s2': 'Run in debug', 'hy.p1s2d': 'The editor appears inside the game window: no separate apps, no lost context.',
  'hy.p1s3': 'Build for release', 'hy.p1s3d': 'The directives strip the editor entirely. Only your game is left, on the backend you chose.',
  'hy.p1f': 'my-game.exe — debug',
  'hy.p1v': 'Recording of the Yotsuba editor running',
  'hy.p1c': 'Real footage of the Yotsuba Hybrid editor. Not a mock-up.',
  'hy.p2t': 'Two layers. Each with its own job.',
  'hy.p2d': '<b>Yotsuba Framework</b> is the modern XNA reimplementation: parallel rendering, Slang shaders and automatic visibility. <b>Yotsuba Engine</b> sits on top: entities, components, systems, scenes, scripting and editor. Hybrid gives you both.',
  'hy.p2s1': 'Your game', 'hy.p2s1d': 'C# and .NET, written once.',
  'hy.p2s2': 'The engine', 'hy.p2s2d': 'Entities, components, systems, scenes, scripting and editor, as an editable C# project inside your solution.',
  'hy.p2s3': 'The backends', 'hy.p2s3d': 'MonoGame, KNI, FNA or Yotsuba Framework, and underneath Vulkan, Metal, DirectX 12 and WebGPU.',
  'hy.p3t': 'Platforms add up, they do not split.',
  'hy.p3d': 'Because you can run your game on MonoGame, KNI, FNA or Yotsuba Framework, every platform any one of the four supports becomes available to your project. You do not pick a backend at the start: you change it when the project asks for it.',
  'hy.p3f': 'What is shown are the announced targets of the project and the capabilities of its backends; it does not mean every destination ships today in a stable release. Consoles require approval, licences and tooling from each manufacturer.',
  'hy.p4t': 'Your code stays yours.',
  'hy.p4d': 'A Hybrid project is ordinary .NET code. You open it in Visual Studio, Rider or VS Code, add any NuGet package and put it in the version control you already use. If one day you want to drop to plain Framework, the whole project comes with you.',
  'hy.p4nk': '04 / Why it matters',
  'hy.p4n': 'Nobody should have to start over because they chose wrong at the beginning.',
  'hy.cpre': 'Yotsuba Hybrid',
  'hy.ch': 'Both things<em>in a single one.</em>',
  'hy.cd': 'Everything in Framework plus the editor inside the game. One payment, a perpetual licence and zero royalties.',
  'hy.cbuy': 'Buy Hybrid', 'hy.ccmp': 'Compare all three',
  'hy.f1': 'Editor', 'hy.f1b': 'In the window', 'hy.f1d': 'Only in DEBUG. RELEASE stays clean.',
  'hy.f2': 'Backends', 'hy.f2d': 'MonoGame · KNI · FNA · Yotsuba',
  'hy.f3': 'Royalties', 'hy.f3d': 'Ship and sell without sharing revenue.',

  /* ----------------------------------------------------------- Engine --- */
  'en.status': 'Early access · in development',
  'en.kick': 'the C# game engine',
  'en.h1a': 'Own your', 'en.h1b': 'Engine.',
  'en.lede': 'Open the editor. Press <b>Play</b>. Ship to desktop and mobile. The script is still <b>real C#</b>, open in your IDE, with your debugger and your NuGet packages.',
  'en.cta1': 'See the walkthrough', 'en.cta2': 'See pricing',
  'en.s1': '2D + 3D', 'en.s2': 'Plain C# / .NET', 'en.s3': 'No royalties',
  'en.art': 'Neon illustration of Yotsuba Engine',
  'en.claim': 'A complete desktop engine with scene, hierarchy, inspector and one-click export — where <b>the project is still ordinary .NET</b> you can open in any IDE.',
  'en.r1': 'Your IDE, your debugger', 'en.r1d': 'Scripts are C# classes. Visual Studio, Rider or VS Code, and any NuGet package.',
  'en.r2': 'Both worlds', 'en.r2d': 'Sprites, tilemaps, glTF animation, PBR materials, particles and physics, in 2D and 3D.',
  'en.r3': 'A readable project', 'en.r3d': 'Ordinary .NET code plus .ytb files, which are JSON you can open and read.',
  'en.r4': 'Not a dead end', 'en.r4d': 'Same engine as Hybrid and Framework. Drop a layer whenever the project asks for it.',
  'en.for': 'From the scene to the exported game',
  'en.actB': 'THE WALKTHROUGH',
  'en.st1': 'Compose', 'en.st1d': 'Every painted thing on the scene is an entity with components. Pick one and the Inspector shows exactly what makes it tick.',
  'en.st2': 'Script', 'en.st2d': 'Behaviour is C#. Attach a script, open it in your IDE and use the debugger you already know.',
  'en.st2f': 'Illustrative snippet.',
  'en.st3': 'Play', 'en.st3d': 'One button runs the scene. Stop it, and it returns to the exact edit state you left.',
  'en.st4': 'Export', 'en.st4d': 'Export to the platforms you target. Some are ready and some experimental: we label every one.',
  'en.exp': 'experimental', 'en.pre': 'preview',
  'en.boxF': 'in the box', 'en.boxH': 'All of this is already built.',
  'en.boxS': 'Early-stage project: the API may still change. Everything below exists in the codebase the Engine is built on.',
  'en.b2': 'Sprites and tilemaps',
  'en.b2d': 'Transforms, zoomable camera, depth ordering, off-screen culling, animation, fonts, text, buttons, Tiled (TMX), TexturePacker and 2D physics with debug drawing.',
  'en.b3': 'glTF and PBR',
  'en.b3d': 'Cameras, primitives, 2.5D sprites, glTF models with skeletal animation, PBR materials, custom shaders, 3D physics with a spatial broad phase, particles, VFX and hardware occlusion queries.',
  'en.bwF': 'Workflow', 'en.bw': 'ECS and editor',
  'en.bwd': 'Scenes, entities, components and systems; editor with console, history, colour picker and 3D model editor; your own scripts; keyboard, mouse, gamepad, touch and gestures; audio with SFX and music channels.',
  'en.cpre': 'Yotsuba Engine',
  'en.ch': 'An engine<em>that really is yours.</em>',
  'en.cd': 'One payment, a perpetual licence and zero royalties. Nobody sends you an invoice the day your game does well.',
  'en.cbuy': 'Buy Engine', 'en.ccmp': 'Compare all three',
  'en.f1': 'Scripts', 'en.f1d': 'Ordinary classes, open in your own IDE.',
  'en.f2': 'Project', 'en.f2d': 'Readable JSON plus .NET code. No closed formats.',
  'en.f3': 'Royalties', 'en.f3d': 'Ship and sell without sharing revenue.',

  /* ---------------------------------------------------------- precios --- */
  'pr.for': 'One payment · perpetual licence · 0 % royalties',
  'pr.actB': 'PRICING',
  'pr.folio': 'pricing',
  'pr.h': 'Pay once.<br><em>It is yours for good.</em>',
  'pr.sub': 'No royalties on what you sell. No per-seat fee. No invoice arriving the day your game does well.',
  'pr.best': 'MOST COMPLETE',
  'pr.once': 'one payment · forever',
  'pr.bdK': 'All three together', 'pr.bdH': 'All of Yotsuba',
  'pr.bdD': 'Framework, Hybrid and Engine together. One purchase, three ways of working, and the freedom to change your mind halfway through a project.',
  'pr.bdWas': 'separately', 'pr.bdSave': 'you save', 'pr.bdBuy': 'Get all three',
  'pr.nk': 'What you will not be paying',
  'pr.n': 'Not a percentage of what you sell, not a fee for each person on the team, not a charge per install, and not somebody else’s splash screen in front of yours.',
  'pr.fine': 'Prices in US dollars, taxes not included. The project is in development: buying now puts you in early access and gets you every new release of the line you bought.',
  'cmp.folio': 'side by side', 'cmp.h': 'All three, side by side.',
  'cmp.sub': 'What changes between them is the editor and how close it puts you to the metal. The engine underneath is the same.',
  'fq.folio': 'questions', 'fq.h': 'What everyone asks first.',
  'fq.sub': 'If yours is missing, write to us and we will add it.',
  'pr.ce': 'Not on sale yet',
  'pr.ch': 'We will tell you<em>on day one.</em>',
  'pr.cd': 'Leave your email and we will write when the store opens, with the final price and no surprises.',
  'pr.ccta': 'Tell me when it launches',
  'pr.g1': 'Licence', 'pr.g1b': 'Perpetual', 'pr.g1d': 'The version you buy is yours even if you stop updating.',
  'pr.g2': 'Commercial use', 'pr.g2b': 'From day one', 'pr.g2d': 'No revenue cap and no studio-size limit.',
  'pr.g3': 'Splash screen', 'pr.g3b': 'Yours', 'pr.g3d': 'We do not put ours in front of yours.',

  /* ------------------------------------------------------ plataformas --- */
  'pl.folio': 'where it reaches', 'pl.h': 'Where it runs, and in what state.',
  'pl.sub': 'The status column is deliberate: we would rather tell you what is experimental than surprise you later.',
  'pl.fine': 'Each row is a host project inside the repository. We do not guarantee feature parity between targets yet. Consoles require approval, licences and tooling from each manufacturer.',

  /* -------------------------------------------------------- comunidad --- */
  'co.for': 'Open source · built in public',
  'co.actB': 'COMMUNITY',
  'co.eyebrow': 'Yotsuba Open Source',
  'co.h': 'Let us build<em>Yotsuba together.</em>',
  'co.d': 'The project is in development and the road is open. Help us sharpen the editor, the backends and the documentation that ties the whole family together.',
  'co.f1': 'Inspect and improve the editor, the ECS and the build workflow.',
  'co.f2': 'Explore the code, report issues and share ideas on GitHub.',
  'co.f3': 'Meet creators and developers who make games in C#.',
  'co.f4': 'Propose changes to the code, the website and the documentation.',
  'co.ctk': 'Write to us directly',
  'co.ceo': 'CEO',
  'co.sup': 'Support the project', 'co.gh': 'View GitHub', 'co.docs': 'Read the documentation',
  'co.mf': 'in motion', 'co.mh': 'This is not a mock-up.',
  'co.ms': 'Real footage of the Yotsuba Hybrid editor running inside the game window.',

  /* ------------------------------------------------------ formulario --- */
  'fo.title': 'Tell me when it launches',
  'fo.desc': 'We write when the store opens and when each release lands. No spam.',
  'fo.name': 'Name', 'fo.nameP': 'Your name',
  'fo.email': 'Email', 'fo.emailP': 'you@email.com',
  'fo.phone': 'Phone', 'fo.opt': '(optional)',
  'fo.want': 'I am interested in', 'fo.submit': 'Notify me'
};
